### ISSUE TITLE
Error: Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by loganpowell** [jacekschae/shadow-reagent#2]
Hi @jacekschae ! Thank you for helping the community out by putting a `shadow-cljs` starter out for us. I've worked with `lein` and `chesnut` in the past with mixed results, so I'm giving shadow a go. I've cloned your project and followed your readme, but get this when running `yarn dev`:

```
λ yarn dev
yarn dev v0.22.0
$ shadow-cljs watch app;
shadow-cljs - config: C:\Users\surface\Projects\clojure\cljs\keechma\shadow-reagent\shadow-cljs.edn version: 2.3.19
shadow-cljs - starting ...
Unrecognized option: --add-modules
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
error Command failed with exit code 1.
```

Any pointers?

**Comment by jacekschae** [comment]
Hey @loganpowell,
Which version of java are you running?

You can run in your terminal `java --version`

most probably it's the line number 3 in `shadow-cljs.edn` 

```clojure
:jvm-opts ["--add-modules" "java.xml.bind"]
```

**Comment by loganpowell** [comment]
```
λ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

What might I change line 3 to?

**Comment by jacekschae** [comment]
You can try by removing it 😃 

Next step would to be to update your Java version. In the docs for [shadow-cljs installation](https://shadow-cljs.github.io/docs/UsersGuide.html#_installation) it says Java SDK (Version 8).

I had run this with Java 9 and now with Java 10 and it seems to be working.

Hope that helps!

**Comment by loganpowell** [comment]
Thank you :)

**Comment by jacekschae** [comment]
np

for more info why this `--add-modules` is required check out this blog post: https://www.deps.co/blog/how-to-upgrade-clojure-projects-to-use-java-9/

**Comment by thheller** [comment]
`--add-modules` should not be required anymore even with Java9.

The CLJS `1.10.238` release `shadow-cljs` uses fixed that.
