### ISSUE TITLE
How to use SCSS in projects

### ISSUE THREAD

**Issue by iptop** [jacekschae/shadow-reagent#4]
I want to better manage CSS.
Is there a plan similar to webpack style-loader?

**Comment by jacekschae** [comment]
Would be grat if shadow-cljs would support that but as I knw it doesn't. Is that right @thheller?

**Comment by thheller** [comment]
It does not. I do have some plans for something that can be used via `:build-hooks` but nothing usable yet.

**Comment by jacekschae** [comment]
Will close this one and point to the https://github.com/thheller/shadow-cljs/issues/353 to track this in the shadow-cljs repo. 

PS. Would love to see shadow-cljs handle css/scss/less wihtout any config just as https://parceljs.org/assets.html 😁
